### PR TITLE
pr-comment-changeToken-warning

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[076f5e6](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/076f5e653aceac089c4b0643d7a7ab900801e097)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/token.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-changeToken-warning/E2E_DocsBranch_Dynamic/token.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/token?branch=pr-en-us-14225) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C28%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201908280546598812-14225%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=8xchJMKhk7L5hxVgC3EpYkkfeGjg4S3ZGPj0IVTgEo4%3D&st=2019-08-28T05%3A42%3A56Z&se=2019-09-28T05%3A47%3A56Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[8b168f8](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/8b168f849c762dd8afb19de8558dada4b3a88a36)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/token.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-changeToken-warning/E2E_DocsBranch_Dynamic/token.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/token?branch=pr-en-us-14225) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C28%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201908280614148113-14225%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=W2tejdbwZdZdFBvjMvHr9MPfmClgrYPCvlP4NThc4d0%3D&st=2019-08-28T06%3A10%3A07Z&se=2019-09-28T06%3A15%3A07Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[e191550](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/e1915506aa940b47b53840fd6c63bc4bba8be1e2)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/token.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-changeToken-warning/E2E_DocsBranch_Dynamic/token.md) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/token?branch=pr-en-us-14225) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C28%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201908280618309678-14225%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=UaKjfGb%2B1ynbl4fnpYYMekQYv8AHR5WZOR%2BC5qgILbI%3D&st=2019-08-28T06%3A14%3A21Z&se=2019-09-28T06%3A19%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[5a6734f](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/5a6734f2d5790159543fe190bdaab889d838468a)_: 

### :white_check_mark: Validation status: passed


For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C28%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201908280620178683-14225%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=lbyFhIPAp5BFENOYRTQuybtnU3Fc70eb%2BzR3iY3masM%3D&st=2019-08-28T06%3A16%3A05Z&se=2019-09-28T06%3A21%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[05b4895](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/05b4895970f5e17de9f340aa1deb10fd8dde943d)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/token.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-changeToken-warning/E2E_DocsBranch_Dynamic/token.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/token?branch=pr-en-us-14225) | [Details](#user-content-7b8393aa-f2ea10ca)

<a id="7b8393aa-f2ea10ca"></a>
### [E2E_DocsBranch_Dynamic/token.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-changeToken-warning/E2E_DocsBranch_Dynamic/token.md)
 - **Line 9**: **[Warning]** `````Invalid file link:(~/invalidlink.md).`````
 - **Line 9**: **[Warning]** `````Invalid file link:(~/invalidlink.md).`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C28%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201908280624181524-14225%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=drbbsQX5YHLohImJjkKm0FWrERMZxU9Rd%2FvsbxMoBYY%3D&st=2019-08-28T06%3A20%3A10Z&se=2019-09-28T06%3A25%3A10Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
