### PR TITLE
Incremental PR: update a resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[5f81cf9](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/5f81cf9422d71417b4c8fa8d505d539144c533a3)_: 

:clock10: **Pending**: waiting for processors ([33](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 33 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd4** [comment]
Docs Build status updates of commit _[5f81cf9](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/5f81cf9422d71417b4c8fa8d505d539144c533a3)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-updateresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/e2e-v2-pr-updateresource/E2E_DocsBranch_Dynamic/incrementalPR-updateresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/b?branch=pr-en-us-18418) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C20%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C202005201820129727-18418%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=V62dH9wafh5kBRs8G724qqlodLH%2BqzT%2FEkK725jhDRM%3D&st=2020-05-20T18%3A17%3A14Z&se=2020-06-20T18%3A22%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by e2ebd3** [comment]
Docs Build status updates of commit _[35c9057](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/35c905798b3ae4f1835e1a60d3a89a961ad649dc)_: 

:clock10: **Pending**: waiting for processors ([26](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 26 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by e2ebd1** [comment]
Docs Build status updates of commit _[35c9057](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/35c905798b3ae4f1835e1a60d3a89a961ad649dc)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-updateresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/e2e-v2-pr-updateresource/E2E_DocsBranch_Dynamic/incrementalPR-updateresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/b?branch=pr-en-us-18418) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2020%5C5%5C21%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C202005211823269501-18418%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=bNjsrejPMx7W2Ui5UBHkfKHbpN%2Bfp%2Fyc%2FqPc2uNRvnY%3D&st=2020-05-21T18%3A20%3A04Z&se=2020-06-21T18%3A25%3A04Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
