### PR TITLE
pr-comment-filemeta-warning

### PR DESCRIPTION
**Pull request by luyajun0205**

### CODE REVIEW

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[67234eb](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/67234ebc81ed3e000ad8b882b1bab54bcbb6780e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/docfx.json](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-filemeta-warning/E2E_DocsBranch_Dynamic/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C28%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201908281353315106-14229%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=Xf9urByBfdpIaZWZu4nWmMnxse1V1WLwv7vKMM%2BZ7%2FI%3D&st=2019-08-28T13%3A49%3A26Z&se=2019-09-28T13%3A54%3A26Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[c75833c](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/c75833c299ff71ca107cc26bb0c0999b73840e8e)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/docfx.json](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-filemeta-warning/E2E_DocsBranch_Dynamic/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C28%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201908281356201567-14229%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6R4kSVALa2kIs0q0ZHt7i%2BGjkpzMJm%2BlDYf0Y%2BznnA0%3D&st=2019-08-28T13%3A52%3A14Z&se=2019-09-28T13%3A57%3A14Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
Docs Build status updates of commit _[6ebb919](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/6ebb9197ecec073199bba68c1fc50eebc9a3f55c)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/docfx.json](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-filemeta-warning/E2E_DocsBranch_Dynamic/docfx.json) | :white_check_mark:Succeeded | |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C29%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201908290150571721-14229%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=2njTZ9nDZCIwxNkA%2FBMTxumE9Bd61zDC6dJtrtyFM8Q%3D&st=2019-08-29T01%3A47%3A40Z&se=2019-09-29T01%3A52%3A40Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[740c18a](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/740c18a17f0c90ddc6bfd80bc879e438e8611191)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/doc/test.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-filemeta-warning/E2E_DocsBranch_Dynamic/doc/test.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/doc/test?branch=pr-en-us-14229) | [Details](#user-content-2428fc4d-d2f29c38)
[E2E_DocsBranch_Dynamic/docfx.json](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-filemeta-warning/E2E_DocsBranch_Dynamic/docfx.json) | :white_check_mark:Succeeded | |

<a id="2428fc4d-d2f29c38"></a>
### [E2E_DocsBranch_Dynamic/doc/test.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-filemeta-warning/E2E_DocsBranch_Dynamic/doc/test.md)
 - **[Warning]** `````unexpected type String for metadata api_name, the expected type is string[]`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C29%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201908290203223892-14229%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=KmrNsXfPUQEnvRyw9QBKi8eAoXj2K83JCofX%2BgklDc0%3D&st=2019-08-29T02%3A00%3A06Z&se=2019-09-29T02%3A05%3A06Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[740c18a](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/740c18a17f0c90ddc6bfd80bc879e438e8611191)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/doc/test.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-filemeta-warning/E2E_DocsBranch_Dynamic/doc/test.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/doc/test?branch=pr-en-us-14229) | [Details](#user-content-2428fc4d-619ec9ed)
[E2E_DocsBranch_Dynamic/docfx.json](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-filemeta-warning/E2E_DocsBranch_Dynamic/docfx.json) | :white_check_mark:Succeeded | |

<a id="2428fc4d-619ec9ed"></a>
### [E2E_DocsBranch_Dynamic/doc/test.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/pr-comment-filemeta-warning/E2E_DocsBranch_Dynamic/doc/test.md)
 - **[Warning]** `````unexpected type String for metadata api_name, the expected type is string[]`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C8%5C30%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201908300243479069-14229%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=fBaq5qNTtn2cdykbePM7ETBNWwykLfjio85JE0s3wcs%3D&st=2019-08-30T02%3A39%3A45Z&se=2019-09-30T02%3A44%3A45Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
