### PR TITLE
e2e: pr warning testTue, 19 Sep 2017 05:05:04 GMT

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by luyajun0205** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/index?branch=pr-en-us-7176) | [Details](#user-content-E2E_DocsBranch_Dynamic%2Findex.md)

<a name="E2E_DocsBranch_Dynamic%2Findex.md"></a>
### [E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 7**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/../nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C19%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201709190505441985-7176%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=j6TTE%2FWycKhhVlwxbRVEskp3FAvqa4PKCIJA7OoDvSY%3D&st=2017-09-19T05%3A01%3A21Z&se=2017-09-20T05%3A11%3A21Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by staceyhong** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/index?branch=pr-en-us-7176) | [Details](#user-content-E2E_DocsBranch_Dynamic%2Findex.md)

<a name="E2E_DocsBranch_Dynamic%2Findex.md"></a>
### [E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 7**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/../nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C19%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201709190517495680-7176%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ITWc5onBW9%2FCxB6qx%2BiKKpfFN3aQ2IsV%2FsIjwnulT88%3D&st=2017-09-19T05%3A13%3A35Z&se=2017-09-20T05%3A23%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/index?branch=pr-en-us-7176) | [Details](#user-content-E2E_DocsBranch_Dynamic%2Findex.md)

<a name="E2E_DocsBranch_Dynamic%2Findex.md"></a>
### [E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 7**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/../nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C19%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201709190523271867-7176%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ZDV3mAipv9d7%2FE%2BrRHGMuKl4OQwXMAA%2FBQEPPHovIvg%3D&st=2017-09-19T05%3A19%3A05Z&se=2017-09-20T05%3A29%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/index?branch=pr-en-us-7176) | [Details](#user-content-E2E_DocsBranch_Dynamic%2Findex.md)

<a name="E2E_DocsBranch_Dynamic%2Findex.md"></a>
### [E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 7**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/../nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C19%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201709190525223886-7176%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=%2Bclq6r5igoY5Su%2Bq46nYg9ILugbN0mHk2bm94ofKpCo%3D&st=2017-09-19T05%3A20%3A58Z&se=2017-09-20T05%3A30%3A58Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/index?branch=pr-en-us-7176) | [Details](#user-content-E2E_DocsBranch_Dynamic%2Findex.md)

<a name="E2E_DocsBranch_Dynamic%2Findex.md"></a>
### [E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 7**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/../nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C19%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201709190527135975-7176%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=xd49Wx37RslMdVAHTCZCsfOcWlMxHnQo0fM%2FdORA%2Fz4%3D&st=2017-09-19T05%3A22%3A50Z&se=2017-09-20T05%3A32%3A50Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-peliao** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/index?branch=pr-en-us-7176) | [Details](#user-content-E2E_DocsBranch_Dynamic%2Findex.md)

<a name="E2E_DocsBranch_Dynamic%2Findex.md"></a>
### [E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 7**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/../nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C19%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201709190534060663-7176%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=YGThcrL3UOLmWJsGxuXRcuYbWLgJwO%2FeHZW3rL6yTtU%3D&st=2017-09-19T05%3A29%3A46Z&se=2017-09-20T05%3A39%3A46Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
### :warning: Validation status: warnings


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/index?branch=pr-en-us-7176) | [Details](#user-content-E2E_DocsBranch_Dynamic%2Findex.md)

<a name="E2E_DocsBranch_Dynamic%2Findex.md"></a>
### [E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarns-e2e/E2E_DocsBranch_Dynamic/index.md)
 - **[Warning]** Ignore metadata: content_type. They are generated by open publish.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 6**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 7**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/../nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2017%5C9%5C20%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201709200213242906-7176%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=Lb%2BZ%2BppfMLMMZ%2FXFgnufsy3eNUF598QWxmCEV99E8ZY%3D&st=2017-09-20T02%3A09%3A05Z&se=2017-09-21T02%3A19%3A05Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
