### PR TITLE
Incremental PR: update a resource

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by Pingpli** [comment]
Docs Build status updates of commit _[688b2b0](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/688b2b07eedf1a55fd15835cc4b3303636748a10)_: 

:clock10: **Pending**: waiting for processors ([26](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 26 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[688b2b0](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/688b2b07eedf1a55fd15835cc4b3303636748a10)_: 

### :white_check_mark: Validation status: passed


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[E2E_DocsBranch_Dynamic/incrementalPR-updateresource.jpg](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/e2e-v2-pr-updateresource/E2E_DocsBranch_Dynamic/incrementalPR-updateresource.jpg) | :white_check_mark:Succeeded | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/b?branch=pr-en-us-14806) |

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C4%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201911041818300360-14806%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=%2BU8Qs02AuxZtkxCwVyxaMB%2BuH%2FJVsvPd5jNbS0LvqDc%3D&st=2019-11-04T18%3A16%3A19Z&se=2019-12-05T18%3A21%3A19Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by ByronWU-PAEX** [comment]
Docs Build status updates of commit _[12355a9](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/12355a99adcec9e33c1f12668078e5b7e3c31920)_: 

:clock10: **Pending**: waiting for processors ([40](https://opportal-sandbox.azurewebsites.net/#/statistic) builds ahead of you) 

 :warning: **Docs Build is busy**, currently there are 40 builds ahead of this one, for more information you can view the Build queue graph on the [Docs Portal](https://opportal-sandbox.azurewebsites.net/#/statistic).

**Comment by luyajun0205** [comment]
Docs Build status updates of commit _[12355a9](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/commits/12355a99adcec9e33c1f12668078e5b7e3c31920)_: 

### :x: Validation status: errors

Please follow instructions [here](https://review.docs.microsoft.com/en-us/help/onboard/faq?branch=master#build--publish) which may help to resolve issue.


File | Status | Preview URL | Details
---- | ------ | ----------- | -------
[]() | :x:Error | | [Details](#user-content-f2cd9968)

<a id="f2cd9968"></a>
###
 - **[Error]** `````Run script failed with no detailed information. Please retry building your content again. If the issue still happens, open a ticket in https://SiteHelp and include the error report for our team to troubleshoot`````

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C11%5C6%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201911061811213133-14806%5Cworkflow_report.html?sv=2016-05-31&sr=b&sig=6R8mYM7qJtJVoW8vmuDJCbbD5LzarIDbXqaywtK9Rvg%3D&st=2019-11-06T18%3A07%3A48Z&se=2019-12-07T18%3A12%3A48Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
