### PR TITLE
Pull request warning status testing

### PR DESCRIPTION
**Pull request by OPSTestPPE**

### CODE REVIEW

**Comment by staceyhong** [comment]
OPS Build status updates of commit _[fcb1a1e](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/pull/13564/commits/fcb1a1e32c6e9e125f1ee7e5ce0f5cf11e5e76fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarning-e2e/E2E_DocsBranch_Dynamic/index.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/index?branch=pr-en-us-13564) | [Details](#user-content-E2E_DocsBranch_Dynamic%2Findex.md) |

<a name="E2E_DocsBranch_Dynamic%2Findex.md"></a>
### [E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarning-e2e/E2E_DocsBranch_Dynamic/index.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 7**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/../nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C2%5C28%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201902281645405044-13564%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=CWXsWhNh%2Bw%2BpCpNC5LisefLND97ZSOTlNiZet%2BerqXM%3D&st=2019-02-28T16%3A41%3A36Z&se=2019-03-31T16%3A46%3A36Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[fcb1a1e](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/pull/13564/commits/fcb1a1e32c6e9e125f1ee7e5ce0f5cf11e5e76fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarning-e2e/E2E_DocsBranch_Dynamic/index.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/index?branch=pr-en-us-13564) | [Details](#user-content-E2E_DocsBranch_Dynamic%2Findex.md) |

<a name="E2E_DocsBranch_Dynamic%2Findex.md"></a>
### [E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarning-e2e/E2E_DocsBranch_Dynamic/index.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 7**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/../nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C3%5C1%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201903010712184405-13564%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=ma5MCLM1eZqdEVxgsoWB4sBCzZJZfELr1d%2Fr2QwxvbM%3D&st=2019-03-01T07%3A09%3A08Z&se=2019-04-01T07%3A14%3A08Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by v-susu** [comment]
OPS Build status updates of commit _[fcb1a1e](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/pull/13564/commits/fcb1a1e32c6e9e125f1ee7e5ce0f5cf11e5e76fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarning-e2e/E2E_DocsBranch_Dynamic/index.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/index?branch=pr-en-us-13564) | [Details](#user-content-E2E_DocsBranch_Dynamic%2Findex.md) |

<a name="E2E_DocsBranch_Dynamic%2Findex.md"></a>
### [E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarning-e2e/E2E_DocsBranch_Dynamic/index.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 7**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/../nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C3%5C1%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201903010717457249-13564%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=cV5KDCeQF4XbMMm6pDMsslEXmE2FF00lqGBcHULyQQo%3D&st=2019-03-01T07%3A14%3A35Z&se=2019-04-01T07%3A19%3A35Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Comment by luyajun0205** [comment]
OPS Build status updates of commit _[fcb1a1e](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/pull/13564/commits/fcb1a1e32c6e9e125f1ee7e5ce0f5cf11e5e76fd)_: 

### :warning: Validation status: warnings


File | Status | Preview URL | Details | Dependent Files
---- | ------ | ----------- | ------- | ---------------
[E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarning-e2e/E2E_DocsBranch_Dynamic/index.md) | :warning:Warning | [View](https://ppe.docs.microsoft.com/en-us/E2E_DocsBranch_Dynamic/index?branch=pr-en-us-13564) | [Details](#user-content-E2E_DocsBranch_Dynamic%2Findex.md) |

<a name="E2E_DocsBranch_Dynamic%2Findex.md"></a>
### [E2E_DocsBranch_Dynamic/index.md](https://github.com/OPS-E2E-PPE/E2E_DocsBranch_Dynamic/blob/prWarning-e2e/E2E_DocsBranch_Dynamic/index.md)
 - **[Warning]** Metadata with following name(s) are not allowed to be set in Yaml header, or as file level metadata in docfx.json, or as global metadata in docfx.json: content_type. They are generated by OPS, so the values set in these 3 places will be ignored. Please remove them from all 3 places to resolve the warning.
 - **[Warning]** the value invalid_type is undefined for metadata content_type
 - **Line 7**: **[Warning]** Invalid file link:(~/../nonexisted1.md).
 - **Line 8**: **[Warning]** Invalid file link:(~/../nonexisted2.md).
 - **Line 9**: **[Warning]** Invalid file link:(~/../nonexisted3.md).

For more details, please refer to the [build report](https://opbuildstoragesandbox2.blob.core.windows.net/report/2019%5C3%5C1%5C76c3c196-55b4-f406-6465-98264dd87b41%5CPullRequest%5C201903010735585424-13564%5Cworkflow_report.html?sv=2015-02-21&sr=b&sig=oNmH4F8B2KbHPRb73%2B2is1lugJkeM2K%2FUuYQ7IqMBME%3D&st=2019-03-01T07%3A32%3A15Z&se=2019-04-01T07%3A37%3A15Z&sp=r).

**Note:** If you changed an existing file name or deleted a file, broken links in other files to the deleted or renamed file are listed only in the full build report.

**Pull request closed without merging**
